POST http://localhost:5112/signup
Content-Type: application/json

{
  "FirstName": "Ivan",
    "LastName": "Smith",
  "Password": "securepassword123",
  "Email": "IvanSmith_92@gmail.com",
  "Role": "Admin"
}

###
DELETE  http://localhost:5112/users/4

###
PUT http://localhost:5112/users/29
Content-Type: application/json

{
  "FirstName": "Joy",
  "LastName": "Doe",
  "Email": "j@gmail.com"
}

###
GET  http://localhost:5112/courses/user/31

###
GET  http://localhost:5112/users

###
PUT  http://localhost:5112/users/9/password
Content-Type: application/json

{
    "NewPassword": "newpassword456"
}

###
POST http://localhost:5112/courses
Content-Type: application/json

{
  "Name": "Introduction to Programming",
  "Description": "A beginner's course on programming concepts.",
  "ImageUrl": "Programming",
  "Price": 99,
  "Link": "https://www.example.com/programming-course"
}